@startuml Pokemon

package data {
    class BattleModel
    class WorldModel

    class Obstacle
    class Player 
    class Position
    class Rect
    class Element
    class CollidingElement

    package pokemon {
        class Pokemon
        class PokemonStats
        class PokemonSpecies
        class PokemonType
        class PokemonMove
        abstract class PokemonExperience
    }
}

package gui { 
    package commands {
        interface Command {
            execute
        }

        class DoNothingCommand
        class PlayerMoveDownCommand
        class PlayerMoveLeftCommand
        class PlayerMoveRightCommand
        class PlayerMoveUpCommand
        class UsePokemonMoveCommand
    }

    package Renderers {
        class BackgroundRenderer
        abstract class BarRenderer
        class BattleMenuRenderer
        class CharRenderer
        class ExperienceBarRenderer
        class HealthBarRenderer
        class PlayerRenderer
        class PokemonRenderer
        class PokemonInfoRenderer
        abstract class Renderer
        class TextRenderer
    }

    class Image
    class Sprite
    class BattleView
    class WorldView
    class GameView
}

package rules {
    class BattleController
    class GameController
    class WorldController
}

class Game

Game *-- GameView
Game *-- GameController

GameController *-- GameView

BattleController *-- BattleView   
BattleController *-- BattleModel  

WorldModel *-- Player

WorldController *-- WorldView   
WorldController *-- WorldModel  

WorldView *-- PlayerRenderer
WorldView *-- BackgroundRenderer
WorldView *-- WorldModel

Element <|-- CollidingElement
Element *-- Position

CollidingElement <|-- Player
CollidingElement <|-- Obstacle
CollidingElement *-- Rect

Player *-- Pokemon 

Pokemon *-- PokemonSpecies
Pokemon *-- PokemonStats
Pokemon *-- PokemonMove

PokemonMove *-- PokemonType

PokemonSpecies *-- PokemonType

Command <|-- DoNothingCommand
Command <|-- PlayerMoveDownCommand
Command <|-- PlayerMoveLeftCommand
Command <|-- PlayerMoveRightCommand
Command <|-- PlayerMoveUpCommand
Command <|-- UsePokemonMoveCommand

Sprite *-- Image

Renderer <|-- PlayerRenderer
Renderer *-- Sprite

PlayerRenderer *-- Player

PokemonRenderer *-- Pokemon

BarRenderer <|-- ExperienceBarRenderer
BarRenderer <|-- HealthBarRenderer

PokemonInfoRenderer *-- TextRenderer
PokemonInfoRenderer *-- ExperienceBarRenderer
PokemonInfoRenderer *-- HealthBarRenderer

TextRenderer *-- CharRenderer

BattleView *-- BackgroundRenderer
BattleView *-- PokemonRenderer
BattleView *-- BattleMenuRenderer

@enduml