@startuml hero

class Application 

class World

class Game

class Element 

class Player

class Creature {
    hitpoints
}

Application *-- Game

Game *-- World

Element <-- Creature
Element <-- Item
Element *-- Position

Creature <-- Player

Player *-- Item

Weapon <-- Item

@enduml