@startuml hero

class com.educorreia.hero.world.World {
    draw()
    processKey()
}

class com.educorreia.hero.world.Position {
    x
    y
}

class com.educorreia.hero.world.Element {
    name
    character

    draw()
}

class com.educorreia.hero.world.Creature {
    hp 
    
    move()
}

class com.educorreia.hero.world.Weapon {
    damage
}

class com.educorreia.hero.world.Item {
    name
}

com.educorreia.hero.Application *-- com.educorreia.hero.Game

com.educorreia.hero.Game *-- com.educorreia.hero.world.World

com.educorreia.hero.world.World *-- com.educorreia.hero.world.Player

com.educorreia.hero.world.Element <-- com.educorreia.hero.world.Creature
com.educorreia.hero.world.Element <-- com.educorreia.hero.world.Item
com.educorreia.hero.world.Element <-- com.educorreia.hero.world.Wall
com.educorreia.hero.world.Element <-- Tile
com.educorreia.hero.world.Element *-- com.educorreia.hero.world.Position

com.educorreia.hero.world.Creature <-- com.educorreia.hero.world.Player
com.educorreia.hero.world.Creature <-- com.educorreia.hero.world.Monster

com.educorreia.hero.world.Player *-- com.educorreia.hero.world.Inventory

com.educorreia.hero.world.Inventory *-- com.educorreia.hero.world.Item

com.educorreia.hero.world.Weapon <-- com.educorreia.hero.world.Item

@enduml